FROM centos:7

MAINTAINER Haris Lihovac <hlihovac@gmail.com>

ENV ver 1.5.0-1.pgsql.docker.x86_64
ADD kannel-$ver.rpm sqlbox-$ver.rpm  /tmp/

RUN yum localinstall -y -q "http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm" && \
    yum install -y -q epel-release && \
    yum install -y -q postgresql94-libs supervisor && \
    yum install -y -q /tmp/kannel-1.5.0-1.pgsql.docker.x86_64.rpm /tmp/sqlbox-1.5.0-1.pgsql.docker.x86_64.rpm && \
    rm -f /tmp/kannel-$var.rpm /tmp/sqlbox-$var.rpm

ADD supervisord.conf /etc/supervisord.conf
CMD supervisord --nodaemon

